### PR TITLE
Leaf/wheatleyinabox/settingpanel

### PR DESCRIPTION
**Pull request by wheatleyinabox**
## Settings Panel Task

*Testing Actions:*
> Click settings button
> Toggle panel & Settings button disappears
> Close button closes panel and makes settings button reappear

### CODE REVIEW

**Review by alimomennasab — COMMENTED** [review]
looks good,  just fix merge errors :)

**Comment by misslame** [comment]
Fix conflicts, get approvals, merge.

**Comment by tapatiohaxx** [comment]
OK This looks good. Good work.

**Review by GuyWhoCode — APPROVED** [review]
Looks all good to me!

**Review by alimomennasab — COMMENTED** [review]
Downloaded it and the settings panel buttons worked as intended. No merge conflicts in any file 👍

**Review by alimomennasab — APPROVED** [review]
(redoing review because I forgot to approve) 
Downloaded it and the settings panel buttons worked as intended. No merge conflicts in any file 👍

**Pull request merged**
